// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "WWDC24",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "WWDC24",
            targets: ["AppModule"],
            bundleIdentifier: "Antoine-Bollengier.WWDC24",
            teamIdentifier: "QDH78FDX85",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .note),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
	    resources: [
		.copy("Resources/getPath"),
		.copy("Resources/kick.m4a"),
		.copy("Resources/kick2.m4a"),
		.copy("Resources/musicPlayingParticleTexture.png"),
		.copy("Resources/mutedParticleTexture.png"),
                .copy("Resources/art.scnassets")
            ]
        )
    ]
)